#!/bin/sh

if [ "$#" -ne 3 ]; then
    echo ""
    echo "Usage: ./team20runscript <suite> <benchmark> <repl_policy>"
    echo "    (suite) benchmarks: "
    echo "      -- (SPEC) bzip2 gcc mcf hmmer sjeng libquantum xalan cactusADM namd soplex calculix lbm"
    echo "      -- (PARSEC) blackscholes bodytrack canneal fluidanimate streamcluster swaptions x264"
    echo "    repl_policy: LRU LFU SRRIP PACIPV SHIP DRRIP NRU Rand TreeLRU"
else
    suite=$1
    bench=$2
    repl=$3

    # your simulation results will be saved to outputs/$repl/$bench/
    if [ "$suite" = "SPEC" ]; then
        mkdir -p outputs/$repl/${bench}
        echo "./build/opt/zsim configs/$repl/${bench}.cfg > outputs/$repl/${bench}/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/$repl/${bench}.cfg > outputs/$repl/${bench}/${bench}.log 2>&1 &
    elif [ "$suite" = "PARSEC" ]; then
        mkdir -p outputs/$repl/${bench}_8c_simlarge
        echo "./build/opt/zsim configs/$repl/${bench}_8c_simlarge.cfg > outputs/$repl/${bench}_8c_simlarge/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/$repl/${bench}_8c_simlarge.cfg > outputs/$repl/${bench}_8c_simlarge/${bench}.log 2>&1 &
    else
        echo "No such benchmark suite, please specify SPEC or PARSEC"
    fi
fi
